name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build your Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/stackoverflown:latest .

      # Push your Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/stackoverflown:latest
